version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: product_order_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # No default database; will be created per service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      bash -c "
        docker-entrypoint.sh postgres & 
        sleep 10;
        psql -U postgres -c 'CREATE DATABASE product_db;';
        psql -U postgres -c 'CREATE DATABASE order_db;'; 
        psql -U postgres -c 'CREATE DATABASE auth_db;'; 
        wait"

  product-service:
    build: ./product-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/product_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - "8084:8084"

  order-service:
    build: ./order-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - "8083:8083"
  authentication-service:
    build: ./authentication-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - "8081:8081"

volumes:
  postgres_data:
    driver: local
